### ISSUE TITLE
Proj4 dependency

### ISSUE THREAD

**Issue by anowacki** [anowacki/BritishNationalGrid.jl#1]
Proj4 installation on Windows [seems tricky](https://github.com/JuliaGeo/Proj4.jl/issues/8).  It would be good to rely on something else which doesn't have this issue.

**Comment by yeesian** [comment]
Hi, we're now providing binaries upstream. We'll be happy if you can give it a spin and let us know if you run into any issues.

**Comment by anowacki** [comment]
Thanks for the update, @yeesian !  Tests are good on Appveyor.
