### ISSUE TITLE
Direct transformation method

### ISSUE THREAD

**Issue by asinghvi17** [anowacki/BritishNationalGrid.jl#9]
It would be great to have a method which simply takes as input `(x, y)` and returns `(lon, lat)` (and the inverse) in order to allow any Julia point type to be roundtripped without going through the struct!  

That would enable pretty simple integration with GeoMakie, IMO.

**Comment by anowacki** [comment]
Yes, this is fair enough.  I am happy to export the internal functions which do this.

**Comment by asinghvi17** [comment]
Thanks!
